apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-park-worker 
spec:
  storageClassName: pure-file
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 30Gi
  hostPath:
    path: /lab/data

