apiVersion: v1
kind: PersistentVolume
metadata:
  name: labtools-k8s
spec:
  storageClassName: pure-file
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 30Gi
  hostPath:
    path: /labtools-k8s

